# Generated by Django 3.0.8 on 2020-07-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('slug', models.SlugField(max_length=125, unique=True, verbose_name='Url')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=125, verbose_name='Модель авто')),
                ('slug', models.SlugField(max_length=125, unique=True, verbose_name='Url')),
                ('year_of_issue', models.IntegerField(verbose_name='Год выпуска')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('gear_box', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=1, verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mans', to='Car.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'ordering': ['manufacturer'],
            },
        ),
    ]
