# Generated by Django 3.0.8 on 2020-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
